version:
  major: 1
  minor: 4
  patch: 0
  prerelease: "release"
jenkins:
  master:
    plugins:
      - configuration-as-code
      - job-dsl
      - plain-credentials
      - github
      - blueocean
      - openstack-cloud
      - pipeline-githubnotify-step
      - timestamper
      - simple-theme-plugin
dev:
  images:
    - datastax/dse-server:6.8.2
    - datastax/cass-config-builder:1.0.2
    - datastax/cassandra-mgmtapi-3_11_7:v0.1.12
