version:
  major: 1
  minor: 3
  patch: 1
  prerelease: "snapshot"
jenkins:
  master:
    plugins:
      - configuration-as-code
      - job-dsl
      - plain-credentials
      - github
      - blueocean
      - openstack-cloud
      - pipeline-githubnotify-step
      - timestamper
      - simple-theme-plugin
dev:
  images:
    - datastax/dse-server:6.8.1
    - datastax/cass-config-builder:1.0.1
    - datastax/cassandra-mgmtapi-3_11_6:v0.1.5
