version:
  major: 0
  minor: 9
  patch: 0
  prerelease: "snapshot"
jenkins:
  master:
    plugins:
      - configuration-as-code
      - job-dsl
      - plain-credentials
      - github
      - blueocean
      - openstack-cloud
      - pipeline-githubnotify-step
      - timestamper
      - simple-theme-plugin
dev:
  images:
    - datastaxlabs/dse-k8s-server:6.8.0-20200316
    - datastaxlabs/dse-k8s-config-builder:0.9.0-20200316
    - datastaxlabs/apache-cassandra-with-mgmtapi:3.11.6-20200316
