apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dsedatacenters.datastax.com
spec:
  group: datastax.com
  names:
    kind: DseDatacenter
    listKind: DseDatacenterList
    plural: dsedatacenters
    singular: dsedatacenter
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            configBuilderImage:
              description: Container image for the DSE config builder init container,
                with host, path, and tag
              type: string
            dseClusterName:
              description: The name by which CQL clients and DSE instances will know
                the DSE cluster. If the same cluster name is shared by multiple DseDatacenters
                in the same Kubernetes namespace, they will join together in a multi-datacenter
                DSE cluster.
              type: string
            parked:
              description: Indicates no DSE nodes should run, like powering down bare
                metal servers. Volume resources will be left intact in Kubernetes
                and re-attached when the cluster is unparked. This is an experimental
                feature that requires that pod ip addresses do not change on restart.
              type: boolean
            racks:
              description: A list of the named racks in the datacenter, representing
                independent failure domains. The number of racks should match the
                replication factor in the keyspaces you plan to create, and the number
                of racks cannot easily be changed once a datacenter is deployed.
              items:
                properties:
                  name:
                    description: The rack name
                    type: string
                required:
                - name
                type: object
              type: array
            repository:
              description: DSE container image repository, with host and path
              type: string
            resources:
              description: Kubernetes resource requests and limits, per DSE pod
              type: object
            size:
              description: Desired number of DSE server nodes
              format: int32
              type: integer
            storageClaim:
              description: Describes the persistent storage request of each DSE node
              properties:
                resources:
                  description: Resource requirements
                  type: object
                storageclassname:
                  type: string
              required:
              - storageclassname
              type: object
            version:
              description: DSE container image tag
              type: string
          required:
          - size
          - dseClusterName
          type: object
        status:
          properties:
            nodes:
              description: The number of the DSE server nodes
              format: int32
              type: integer
          required:
          - nodes
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
