name: Kind Integration Tests
on:
  push:
    branches:
      - master
      - "1.4.x"
      - "1.5.x"
  pull_request:
    branches: [ master ]
jobs:
  kind_integration_tests:
    strategy:
      matrix:
        integration_test:
        - smoke_test_dse
        - smoke_test_oss
      # let other tests continue to run
      # even if one fails
      fail-fast: false
    name: ${{ matrix.integration_test }}
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.14
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v2
        if: github.event_name != 'pull_request'
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Install Mage
        run: |
          cd /tmp
          wget https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz
          tar -xvf mage_1.9.0_Linux-64bit.tar.gz
          mkdir -p $GOPATH/bin
          mv mage $GOPATH/bin/mage
          chmod +x $GOPATH/bin/mage
      - name: Install kind
        env:
          M_K8S_FLAVOR: kind
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          mage k8s:installTool
      - name: Setup cluster, build and load operator image
        env:
          M_K8S_FLAVOR: kind
          M_KIND_CONFIG: tests/testdata/kind/kind_config_1_worker.yaml
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          mage k8s:setupEmptyCluster
      - name: Run integration test ( ${{ matrix.integration_test }} )
        env:
          M_K8S_FLAVOR: kind
          M_LOAD_TEST_IMAGES: true
          M_INTEG_DIR: ${{ matrix.integration_test }}
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          mage integ:run
      - name: Archive k8s logs
        if: ${{ always() }}
        # actions/upload-artifact@v1
        uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5
        with:
          name: k8s-logs
          path: ./build/kubectl_dump
